# Generated by Django 6.0.6 on 2026-07-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True)),
                ('turi', models.CharField(max_length=50)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soni', models.PositiveIntegerField()),
                ('chegirma_foizi', models.PositiveIntegerField(default=0)),
                ('tavsifi', models.TextField(blank=True)),
                ('sotuvda', models.BooleanField(default=True)),
            ],
        ),
    ]
